# Generated by Django 6.0 on 2026-01-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinCare_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='concern',
        ),
        migrations.AddField(
            model_name='product',
            name='concerns',
            field=models.ManyToManyField(blank=True, to='skinCare_app.concern'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='concern',
            table='concerns',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
