# Generated by Django 6.0 on 2026-01-27 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skinCare_app', '0002_remove_product_concern_product_concerns_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concern',
            name='created_at',
        ),
    ]
