# Generated by Django 6.0 on 2026-01-27 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinCare_app', '0003_remove_concern_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductConcern',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('concern', models.ForeignKey(db_column='concern_id', on_delete=django.db.models.deletion.CASCADE, to='skinCare_app.concern')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='skinCare_app.product')),
            ],
            options={
                'db_table': 'products_concerns',
                'unique_together': {('product', 'concern')},
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='concerns',
            field=models.ManyToManyField(blank=True, related_name='products', through='skinCare_app.ProductConcern', to='skinCare_app.concern'),
        ),
    ]
